version: '3.5'
services:
  user-debug:
    build: .
    volumes: 
      - .:/var/www/gateway
    restart: always
    hostname: midia
    command: npm run start:debug
    ports: 
      - 9226:9226
    env_file:
      - .env
    networks:
      - backend
  user-dev:
    build: .
    volumes: 
      - .:/var/www/gateway
    restart: always
    hostname: midia
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:
    external:
      name: cartografia-network